---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ .Values.dsName }}
  labels:
    app: {{ .Values.appName }}
spec:
  name: {{ .Values.dsName }}.yaml
  datasources:
    - name: InfluxDB
      type: influxdb
      access: proxy
      database: {{ .Values.influxdb.db.dbName }}
      user: {{ .Values.influxdb.db.adminUser }}
      url: http://influxdb-{{ .Release.Name }}:8086
      jsonData:
        httpMode: GET
      secureJsonData:
        password: {{ .Values.influxdb.db.adminUserPassword }}
