sudo: required
before_install:
- sudo apt-get install -y tar jq curl 
addons:
  apt:
    update: true
before_script: 
- ./ci-dependencies.sh
- cat grafana-dashboard.json | jq .
deploy:
- provider: script
  script: "./ci-deploy.sh"
  skip_cleanup: true
  on:
    branch: master
