sudo: required
before_install:
- sudo apt-get install -y tar jq curl 
addons:
  apt:
    update: true
script: 
- ./ci-dependencies.sh
deploy:
- provider: script
  script: "./ci-deploy.py"
  skip_cleanup: true
  on:
    branch: master
