sudo: required
before_install:
- sudo apt-get install -y tar jq curl 
addons:
  apt:
    update: true
install:
- curl -O https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/oc/4.3/linux/oc.tar.gz && \ 
    tar xzvf oc.tar.gz -C /usr/local/bin/ && \ 
    rm -f oc.tar.gz
script:
- jq validate grafana-dashboard.json
deploy:
- provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    branch: master
