# Grafana will be deployed using the operator
appName: grafana
dsName: datasource
dashboardName: dashboard
service:
  port: 3000
ingress:
  host: <url>
adminUser: admin
adminPassword: password

influxdb:
  appName: influxdb
  image:
    repository: docker.io/library/influxdb:latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8086
    portName: 8086-tcp
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    host: <url>
  db:
    dbName: temperature
    adminUser: admin
    adminUserPassword: password
    url: http://influxdb:8086