---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: influxdb-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - env:
        - name: INFLUXDB_DB
          value: {{ .Values.db.dbName }}
        - name: INFLUXDB_ADMIN_USER
          value: {{ .Values.db.adminUser }}
        - name: INFLUXDB_ADMIN_PASSWORD
          value: {{ .Values.db.adminUserPassword }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.appName }}
        ports:
        - containerPort: 8086
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-volume
      volumes:
      - name: influxdb-volume
        persistentVolumeClaim:
          claimName: pvc-influxdb-{{ .Release.Name }}
