---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influxdb-{{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | default "5G" }}
  volumeMode: Filesystem
{{- if .Values.storage.storageClass }}
  storageClassName: "{{ .Values.storage.storageClass }}"
{{- end }}