apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.appName }}
  name: influxdb-{{ .Release.Name }}
spec:
  host: {{ .Values.ingress.host }}
  port:
    targetPort: {{ .Values.service.portName }}
  tls:
    termination: edge
  to:
    kind: Service
    name: influxdb-{{ .Release.Name }}
    weight: 100
  wildcardPolicy: None
