appName: influxdb
image:
  repository: docker.io/library/influxdb:latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8086
  portName: 8086-tcp

storage:
  storageClass: local-sc
  size: 5G

podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  host: <url>

db:
  dbName: temperature
  adminUser: admin
  adminUserPassword: password
  url: http://influxdb:8086